name: redacted_codetest
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.1
  get_it: ^7.2.0
  graphql: ^5.1.1
  equatable: ^2.0.5
  cloud_firestore: ^4.2.0
  process_run: ^0.12.3+2
  firebase_core: ^2.4.0
  connectivity_plus: ^2.2.1
  intl: ^0.18.0
  bloc_test: ^9.1.0
  mockito: ^5.3.2
  fake_cloud_firestore: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/mocks/
