// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuqfbwKdEurXuame5IWUUN_fPncNf7B0U',
    appId: '1:141843367287:web:f9fa2864c3ac9e1f9a8d72',
    messagingSenderId: '141843367287',
    projectId: 'thinkific-code-test',
    authDomain: 'thinkific-code-test.firebaseapp.com',
    storageBucket: 'thinkific-code-test.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdVXFAZ_GTjr9QlFZ7kWega4BUgiK_5G4',
    appId: '1:141843367287:android:a76efe05a6cf339a9a8d72',
    messagingSenderId: '141843367287',
    projectId: 'thinkific-code-test',
    storageBucket: 'thinkific-code-test.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZHxUbYqgmQ4dVoIOzHMNb2Jwv2_jZ2mo',
    appId: '1:141843367287:ios:b1cb72c7f6d49ab69a8d72',
    messagingSenderId: '141843367287',
    projectId: 'thinkific-code-test',
    storageBucket: 'thinkific-code-test.appspot.com',
    iosClientId: '141843367287-rcofro4p382inknl97qak2ont17blj5a.apps.googleusercontent.com',
    iosBundleId: 'com.example.thinkificCodetest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZHxUbYqgmQ4dVoIOzHMNb2Jwv2_jZ2mo',
    appId: '1:141843367287:ios:b1cb72c7f6d49ab69a8d72',
    messagingSenderId: '141843367287',
    projectId: 'thinkific-code-test',
    storageBucket: 'thinkific-code-test.appspot.com',
    iosClientId: '141843367287-rcofro4p382inknl97qak2ont17blj5a.apps.googleusercontent.com',
    iosBundleId: 'com.example.thinkificCodetest',
  );
}
